import * as fsAsync from "node:fs/promises";

/** A helper class for building consistently indented text */
export class IndentedStringWriter {
    private indent = 0;
    private current = "";
    private lineStarted = false;

    /**
     * Initializes a new {@link IndentedStringWriter}
     * @param indentString The string to prepend to lines per indent level - defaults to four spaces
     */
    constructor(readonly indentString: string = "    ") {}

    /** Increase the indent level */
    increaseIndent(): void {
        this.indent += 1;
    }

    /** Decrease the indent level */
    decreaseIndent(): void {
        if (this.indent === 0) {
            throw new Error("cannot indent below 0");
        }
        this.indent -= 1;
    }

    /** Write the appropriate number of indent strings for this line */
    private writeIndent(): void {
        this.current += this.indentString.repeat(this.indent);
        this.lineStarted = true;
    }

    /**
     * Write text without terminating the current line
     * @param s The text to write
     */
    write(s: string): void {
        if (!this.lineStarted) {
            this.writeIndent();
        }
        this.current += s;
    }

    /**
     * Write text and terminate the current line
     * @param s The text to write or `undefined` to terminate the current line
     */
    writeLine(s?: string): void {
        if (s !== undefined) {
            this.write(s);
        }
        this.current += "\n";
        this.lineStarted = false;
    }

    /**
     * Write multiple lines and can include indention changes
     * @param lines A variable list of line items - each item can be
     *   - `string` - text to write
     *   - `undefined` - a blank line with no indentation
     *   - {@link IncreaseIndent} / {@link DecreaseIndent} - modify the indent level for following lines without writing text
     */
    writeLines(
        ...lines: (string | typeof IncreaseIndent | typeof DecreaseIndent | undefined)[]
    ): void {
        for (const line of lines) {
            if (line === IncreaseIndent) {
                this.increaseIndent();
                continue;
            } else if (line === DecreaseIndent) {
                this.decreaseIndent();
                continue;
            }
            this.writeLine(line);
        }
    }

    /**
     * Get a copy of the current string
     * @returns A copy of the current string
     */
    getString(): string {
        return this.current;
    }

    /**
     * Write the contents of the current string to a file
     * @param file The file to write to
     * @returns A promise that resolves when writing is complete
     */
    async writeFileAsync(file: string): Promise<void> {
        await fsAsync.writeFile(file, this.current, { encoding: "utf-8" });
    }

    /** Writes the standard header for generated files */
    writeGeneratedHeaderComment(): void {
        this.writeLines(
            "// GENERATED BY `vscode-manifest-types`",
            "// DO NOT MODIFY BY HAND",
            undefined
        );
    }
}

/** Used for {@link IndentedStringWriter.writeLines} to increase the indent level without writing text */
export const IncreaseIndent: unique symbol = Symbol();

/** Used for {@link IndentedStringWriter.writeLines} to decrease the indent level without writing text */
export const DecreaseIndent: unique symbol = Symbol();
