import * as fsAsync from "node:fs/promises";

export class IndentedStringWriter {
    private indent = 0;
    private current = "";
    private lineStarted = false;

    constructor(readonly indentString: string = "    ") {}

    increaseIndent(): void {
        this.indent += 1;
    }

    decreaseIndent(): void {
        this.indent -= 1;
    }

    private writeIndent(): void {
        this.current += this.indentString.repeat(this.indent);
        this.lineStarted = true;
    }

    write(s: string): void {
        if (!this.lineStarted) {
            this.writeIndent();
        }
        this.current += s;
    }

    writeLine(s?: string | typeof IncreaseIndent | typeof DecreaseIndent): void {
        if (s === IncreaseIndent) {
            this.increaseIndent();
            return;
        } else if (s === DecreaseIndent) {
            this.decreaseIndent();
            return;
        }
        if (s !== undefined) {
            this.write(s);
        }
        this.current += "\n";
        this.lineStarted = false;
    }

    writeLines(
        ...lines: (string | typeof IncreaseIndent | typeof DecreaseIndent | undefined)[]
    ): void {
        for (const line of lines) {
            this.writeLine(line);
        }
    }

    getString(): string {
        return this.current;
    }

    async writeFileAsync(file: string): Promise<void> {
        await fsAsync.writeFile(file, this.current, { encoding: "utf-8" });
    }

    writeGeneratedHeaderComment(): void {
        this.writeLines(
            "// GENERATED BY `vscode-manifest-types`",
            "// DO NOT MODIFY BY HAND",
            undefined
        );
    }
}

export const IncreaseIndent: unique symbol = Symbol();

export const DecreaseIndent: unique symbol = Symbol();
